"""empty message

Revision ID: 5cd52864bbda
Revises: 8c9b2f7a414d
Create Date: 2017-10-14 11:57:03.733194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd52864bbda'
down_revision = '8c9b2f7a414d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'name')
    # ### end Alembic commands ###
